### ISSUE TITLE
[vim-hug-neovim-rpc] rpc method [nvim_buf_line_count] not implemented in pythonx/neovim_rpc_methods.py. Please send PR or contact the mantainer.

### ISSUE THREAD

**Issue by fcying** [roxma/vim-hug-neovim-rpc#16]
vim version: vim 8.0.1350 install by linuxbrew --with-python3

python3:  /home/swguest/.linuxbrew/bin/python3

has('pythonx') 1
has('python3') 1

set pyxversion=3

:echo neovim_rpc#serveraddr()
127.0.0.1:59269

**Comment by roxma** [comment]
Which commit of this plugin are you using?

`nvim_buf_line_count` is supported with the latest version.

I cannot reproduce the issue.

**Comment by fcying** [comment]
ncm version:
commit 0acab11a71dea6bd04264f1e38669bdcbd50f1fa
    add ncm-R link
rpc version:
commit 8aae46b82a50c3a2438331ee8067f5efccbe4cba
    update incompatibility for python None.


On my own computer, ncm work fine with vim && neovim.

On my office server, I'm not a sudo user,  so I install vim8 neovim python3 by linuxbrew,  ncm can not work with vim8, work fine with neovim.

**Comment by Shougo** [comment]
> commit 8aae46b

vim-hug-neovim-rpc is too old.
The plugin version up is required.

**Comment by fcying** [comment]
It's work after upgrade rpc, thanks~
