### ISSUE TITLE
rpc method nvim_buf_line_count not implemented

### ISSUE THREAD

**Issue by Shougo** [roxma/vim-hug-neovim-rpc#19]
I have tested https://github.com/Shougo/deoplete.nvim/pull/602.

But "rpc method `[nvim_buf_line_count]` not implemented in pythonx/neovim_rpc_methods.py" is displayed.
Could you implement the feature?

**Comment by roxma** [comment]
#16 

This rpc method has been added. Which version you're using?

**Comment by Shougo** [comment]
Oh, OK.
I will update it later.
