### ISSUE TITLE
`scall` command

### ISSUE THREAD

**Issue by ichizok** [roxma/vim-hug-neovim-rpc#26]
https://github.com/roxma/vim-hug-neovim-rpc/blob/e8af9b262bfcae1b2f5c755a099cba9687c33a0a/pythonx/neovim_rpc_server.py#L122

Typo? It causes E488 error on my environment.

**Comment by roxma** [comment]
I've pushed an update. Please test it

**Comment by ichizok** [comment]
I confirmed fix. Thank you!
