### ISSUE TITLE
failed executing: pythonx import neovim (archlinux)

### ISSUE THREAD

**Issue by Manu-sh** [roxma/vim-hug-neovim-rpc#28]
Im on Vim 8.1:

Following statements are true:
```viml
has('pythonx')
has('python')
has('python3')
```
neovim seem to be installed correctly:
```python
Python 2.7.15 (default, May  1 2018, 20:16:04) 
[GCC 7.3.1 20180406] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> 

Python 3.6.5 (default, May 11 2018, 04:00:52) 
[GCC 8.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import neovim
>>> 
```

When i open vim i get this error:
```viml
[vim-hug-neovim-rpc] failed executing: pythonx import neovim
[vim-hug-neovim-rpc] Vim(pythonx):Traceback (most recent call last)
```

As cfg i have:
```viml
" Deoplete
set pyxversion=3
set encoding=utf-8
let g:python_host_prog = "/usr/bin/python2"
let g:python3_host_prog = "/usr/bin/python3"
let g:deoplete#enable_at_startup = 1

Plugin 'roxma/nvim-yarp'
Plugin 'roxma/vim-hug-neovim-rpc'
Plugin 'Shougo/deoplete.nvim'
```

**Comment by Shougo** [comment]
You should test `pythonx import neovim` in Vim command line.
It seems does not work.

It is not vim-hug-neovim-rpc problem.

**Comment by Shougo** [comment]
I have tested `pythonx import neovim` in Manjaro Linux.  It does work.

**Comment by Manu-sh** [comment]
I have typed `:pythonx import neovim` and this is the output:
```python
Traceback (most recent call last):                                                                                                                                           
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/neovim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/home/user/.local/lib/python3.6/site-packages/neovim/msgpack_rpc/__init__.py", line 10, in <module>
    from .session import ErrorResponse, Session
  File "/home/user/.local/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 6, in <module>
    import greenlet
ImportError: /usr/lib/python3.6/site-packages/greenlet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyExc_ValueError
```

**Comment by Manu-sh** [comment]
so i should close the issue ?

**Comment by Shougo** [comment]
Yes.

You need to reinstall `greenlet` library.

**Comment by Manu-sh** [comment]
yes i have reinstalled `greenlet` library and now work properly (thx)

**Comment by ghost** [comment]
I'm having the same issue, but with /usr/lib/python3.7. Reinstalling greenlet did nothing to help. Everything else is the same as this post.

**Comment by qJkee** [comment]
Same here
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/neovim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/usr/lib/python3/dist-packages/neovim/msgpack_rpc/__init__.py", line 10, in <module>
    from .session import ErrorResponse, Session
  File "/usr/lib/python3/dist-packages/neovim/msgpack_rpc/session.py", line 7, in <module>
    import greenlet
ModuleNotFoundError: No module named 'greenlet'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'
Original exception was:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/neovim/__init__.py", line 11, in <module>
    from .msgpack_rpc import (ErrorResponse, child_session, socket_session,
  File "/usr/lib/python3/dist-packages/neovim/msgpack_rpc/__init__.py", line 10, in <module>
    from .session import ErrorResponse, Session
  File "/usr/lib/python3/dist-packages/neovim/msgpack_rpc/session.py", line 7, in <module>
    import greenlet
ModuleNotFoundError: No module named 'greenlet'
```

**Comment by Thesola10** [comment]
For those who found this ticket trying to solve this kind of crash:

Don't use the `pip` version of `greenlet` on Arch.

**Comment by ghost** [comment]
by installing `sudo pacman -S python-greenlet` it works, but when I use it inside virtualenv it fails with above errors

**Comment by Thesola10** [comment]
> by installing `sudo pacman -S python-greenlet` it works, but when I use it inside virtualenv it fails with above errors

While pacman _does_ install `greenlet`, it only does so in the same place as `pip` would. Loading a virtualenv discards packages such as `greenlet` so you have to link the Arch version into your virtualenv as well.

**Comment by ghost** [comment]
> While pacman _does_ install `greenlet`, it only does so in the same place as `pip` would. Loading a virtualenv discards packages such as `greenlet` so you have to link the Arch version into your virtualenv as well.

Fantastic! Cheers, this worked perfectly, I was actually not aware of this problem, just starting out with virtual envs tbh.

For anyone still needing this solution install your virtual env (depending on provider) in similar fashion:
`mkvirtualenv --system-site-packages <env-name>`
`--system-site-packages` flag enables system wide installed packages, which in our case is `python-greenlet`

**Comment by anbuinf** [comment]
by direct reinstalling `greenlet` library or installing `sudo pacman -S python-greenlet` are not worked for me because both use the precompiled wheel/binary.

##### As per pip install guidance this solution worked for me

``` console 
pip3 uninstall pynvim
cd ~/.local/lib/python3.7/site-packages/
rm -r greenlet-0.4.15-py3.7.egg-info greenlet.cpython-37m-x86_64-linux-gnu.so
pip3 install --user --no-binary :all: pynvim
```

Reference
https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-binary
https://www.archlinux.org/packages/community/x86_64/python-greenlet/files/
https://bbs.archlinux.org/viewtopic.php?id=232873

**Comment by anbuksv** [comment]
by direct reinstalling `greenlet` library or installing `sudo pacman -S python-greenlet` are not worked for me because both use the precompiled wheel/binary.

##### As per pip install guidance this solution worked for me

``` console 
pip3 uninstall pynvim
cd ~/.local/lib/python3.7/site-packages/
rm -r greenlet-0.4.15-py3.7.egg-info greenlet.cpython-37m-x86_64-linux-gnu.so
pip3 install --user --no-binary :all: pynvim
```

Reference
https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-binary
https://www.archlinux.org/packages/community/x86_64/python-greenlet/files/
https://bbs.archlinux.org/viewtopic.php?id=232873

**Comment by StarryLeo** [comment]
@anbuksv Thank you for your answer, my question is the same as yours. But I don't have this file `greenlet-0.4.15-py3.7.egg-info` , I do `rm -rf greenlet-0.4.15.dist-info`, and deoplete work. But I do `:echo neovim_rpc#serveraddr()`, I get `/tmp/veSlECq/2`. @roxma

**Comment by etorth** [comment]
This is sooooo annoying!
I followed @anbuksv 's solution, but still:
```bash
[vim-hug-neovim-rpc] Vim(pythonx):ImportError: No module named neovim
Error detected while processing function deoplete#enable[9]..deoplete#initialize[1]..deoplete#init#_initialize[10]..<SNR>64_init_internal_variables[28]..neovim_rpc#serveraddr:
line   18:
E605: Exception not caught: [vim-hug-neovim-rpc] requires one of `:pythonx import [pynvim|neovim]` command to work
Press ENTER or type command to continue
```
but funny thing is, if I manually type:
:python3 import pynvim

in vim, seems nothing wrong...

**Comment by korsmakolnikov** [comment]
Same issue on macos mojave

**Comment by chungonion** [comment]
> by direct reinstalling `greenlet` library or installing `sudo pacman -S python-greenlet` are not worked for me because both use the precompiled wheel/binary.
> 
> ##### As per pip install guidance this solution worked for me
> ```
> pip3 uninstall pynvim
> cd ~/.local/lib/python3.7/site-packages/
> rm -r greenlet-0.4.15-py3.7.egg-info greenlet.cpython-37m-x86_64-linux-gnu.so
> pip3 install --user --no-binary :all: pynvim
> ```
> 
> Reference
> https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-no-binary
> https://www.archlinux.org/packages/community/x86_64/python-greenlet/files/
> https://bbs.archlinux.org/viewtopic.php?id=232873

Worked even on mac, thanks for your help!!!

**Comment by Shougo** [comment]
@korsmakolnikov Please read this.
https://github.com/roxma/vim-hug-neovim-rpc/issues/36
