### ISSUE TITLE
Error entering insert mode macvim

### ISSUE THREAD

**Issue by dylan-chong** [roxma/vim-hug-neovim-rpc#29]
<img width="1050" alt="screen shot 2018-06-21 at 12 18 51 pm" src="https://user-images.githubusercontent.com/17482349/41691208-83000d86-754d-11e8-9d0e-70c20e3fda3f.png">

**Comment by dylan-chong** [comment]
seems to be caued my call deopete#enable()

**Comment by Shougo** [comment]
Please upload :messages result.

**Comment by dylan-chong** [comment]
It appears that the comment that I thought I put here a few days ago didn't appear.

Anyway, see this comment for more information about this issue, and :messages https://github.com/roxma/vim-hug-neovim-rpc/pull/30#issuecomment-399736051
