### ISSUE TITLE
neovim imp error

### ISSUE THREAD

**Issue by zkdfbb** [roxma/vim-hug-neovim-rpc#33]
when start vim it shows:

[vim-hug-neovim-rpc] failed executing: pythonx import neovim
[vim-hug-neovim-rpc] Vim(pythonx):/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative u
ses

**Comment by roxma** [comment]
Duplicate #28  #25  #3

Read the requirements section. This is not vim-hug-neovim-rpc issue.
