### ISSUE TITLE
Don't have valid neovim_rpc#serveraddr()

### ISSUE THREAD

**Issue by hughshuwang** [roxma/vim-hug-neovim-rpc#42]
Ubuntu 18.04 & Vim 8, trying to use ncm2, ncm-R, and Nvim-R for R development. As for vim-hug-neovim-rpc, when I ran :echo neovim_rpc#serveraddr(), didn't get the address but "/tmp/vPac7C8/0" instead. What does it mean and is it the reason for ncm not working?

FYI, I can run neovim in python3. :echo has('python3') returns 1.

Thanks, appreciate your time!

**Comment by roxma** [comment]
ncm2 does not support ncm plugins including ncm-r
