### ISSUE TITLE
The echo neovim_rpc#serveraddr() test results in /tmp/vmrUX9X/2

### ISSUE THREAD

**Issue by Millani** [roxma/vim-hug-neovim-rpc#48]
After installing `vim-hug=neovim-rpc`, I proceeded to the mentioned test for a valid installation:

> Use `:echo neovim_rpc#serveraddr()` to test the installation. It should print something like `127.0.0.1:51359`.

However, what I get is `/tmp/vmrUX9X/2`, quite different from what seems to be expected. I am not entirely sure how problematic that can be, but indeed `ncm-R` is not working with `vim-hug-neovim-rpc`.

**Comment by Shougo** [comment]
> However, what I get is `/tmp/vmrUX9X/2`

I get the similar path, but vim-hug-neovim-rpc works as expected.

**Comment by roxma** [comment]
`/tmp/vmrUX9X/2` is what it does on systems with unix domain socket now.

>  indeed ncm-R is not working with vim-hug-neovim-rpc

This is another issue. You need to open a issue either on ncm2 repo or ncm-R repo with more information.
