### ISSUE TITLE
Is there an option to turn vim-hug-neovim-rpc off?

### ISSUE THREAD

**Issue by kuator** [roxma/vim-hug-neovim-rpc#50]
So, I am using deoplete and coc. And I want to use deoplete for some filetypes, and coc for others.
What I want to do is use coc.vim for javascript, coc has its vim-node-rpc client, which is conflicting with vim-hug-neovim-rpc. I need vim-hug for deoplete to work in vim.
Now, what I do now is remove vim-hug from rtp. But, I don't think it's the right way to do it.
```
autocmd FileType javascript set runtimepath-=~/.config/nvim/repos/github.com/roxma/vim-hug-neovim-rpc
autocmd FileType javascript set runtimepath-=~/.config/nvim/repos/github.com/roxma/nvim-yarp
```
Is there a way to turn it off?

**Comment by roxma** [comment]
I don't think this plugin conflicts  with vim-node-rpc.  There's no need to turn it off. 

If it does conflicts with vim-node-rpc. You should open an issue and provide detailed information.
