### ISSUE TITLE
Vim-node-rpc

### ISSUE THREAD

**Issue by kuator** [roxma/vim-hug-neovim-rpc#51]
https://github.com/roxma/vim-hug-neovim-rpc/issues/50#issue-429399289
So, I commeted these lines
```
" autocmd FileType javascript set runtimepath-=~/.config/nvim/repos/github.com/roxma/vim-hug-neovim-rpc
" autocmd FileType javascript set runtimepath-=~/.config/nvim/repos/github.com/roxma/nvim-yarp

```
When, I open vim, these are the messages I get
```
[vim-hug-neovim-rpc] rpc method [nvim_set_client_info] not implemented in pythonx/neovim_rpc_methods.py. Please send PR or contact the
 mantainer.
[vim-hug-neovim-rpc] rpc method [nvim_get_vvar] not implemented in pythonx/neovim_rpc_methods.py. Please send PR or contact the mantai
ner.
[vim-node-coc]: Channel create error: request nvim_get_vvar - nvim_get_vvar not implemented

```

**Comment by roxma** [comment]
You need to post minimal vimrc so that I can reproduce the issue

**Comment by roxma** [comment]
By the way, you cannot disable a plugin by removing it in runtimepath. There's no way to unload it. I've never seen  any vim/nvim plugin designed with unload in mind.

**Comment by roxma** [comment]
If you need to disable deoplete/coc on specific buffer, you should read deoplete/coc's documentation on how to disable and enable them, for example: https://github.com/Shougo/deoplete.nvim/issues/77

**Comment by kuator** [comment]
Okay, I guess I should read the documentation about how to disable certain plugins. Sorry for wasting your time.
