### ISSUE TITLE
Android Issue - getaddrinfo()

### ISSUE THREAD

**Issue by icthus56** [roxma/vim-hug-neovim-rpc#69]
Hello, 
Not the fault of neovim-rpc.
I am trying to get this working on a chromebook running ChromeOS under Termux.
When executing "echo neovim_rpc#serveraddr()", I get:
~
[No Name]                                                                                                                                                  0,0-1          All
Error detected while processing function neovim_rpc#serveraddr:
line   29:
E901: getaddrinfo() in channel_open(): Invalid value for ai_flags
line   32:
E906: not an open channel
/data/data/com.termux/files/usr/tmp/vbxd8DR/0
Press ENTER or type command to continue

Is there a way I can work around this, do I need to rewrite the call to getaddrinfo() so that its compatible?

Thanks for any pointers you can give me.

Sam

**Comment by Shougo** [comment]
Hm. Vim8 seems not support Android environment.
You can fix the source code.  It is open source.
https://github.com/vim/vim/blob/02b4d9b18a03549b68e364e428392b7a62766c74/src/channel.c#L981

Or you can use neovim instead.

**Comment by icthus56** [comment]
Vim8 does not directly support Android, this issue is not related to neovim_rpc.
