### ISSUE TITLE
Document vim install steps for win32 users

### ISSUE THREAD

**Issue by MartyLake** [roxma/vim-hug-neovim-rpc#71]
Hello,

**TDLR: For all windows users, install vim64bit and python64bit before running `python3 -m pip install pynvim` in a normal windows cmd.**

Long story:

After multiple hours of searching, span accross multiple trials last year, and this year, I finally found the solution of a perplexing issue. Maybe it’s worth mentioning in the readme ?

I had both python32 and python64 installed on my system, and was using gvim-32bit (as blindly adviced in https://github.com/vim/vim-win32-installer/releases ). 

Running `:py3 import pip; pip.main(['install', '--user', 'pynvim'])` from vim would trigger some errors because `pip.main` is not available anymore after pip 10. after correcting this, then some errors where pip complains that it’s not a tty.

However, running `python3 -m pip install pynvim` from the windows cmd works fine !

Then, from gvim-32bit, `:python3 import pynvim ` would complain about `greenlet` not being installed. However, from gvim-32bit still, running `:terminal` then from this cmd run `python3` then `import pynvim` would work fine !

After reading some forums, I realised that greenlet is probably some native code, and as such has to be the correct architecture. Even if this is wrong, I installed gvim-64bit instead, and now everything is good, all good.

Maybe none on the maintainers of this amazing lib is in my situation, but I though it would help other users like me (for example futur me).
You may close this issue if there is nothing more to add.

Best,

**Comment by Shougo** [comment]
Please create the PR for it.  This is open source solution.

> Running :py3 import pip; pip.main(['install', '--user', 'pynvim']) from vim would trigger some errors because pip.main is not available anymore after pip 10. after correcting this, then some errors where pip complains that it’s not a tty.

The solution is used for users who don't want to check `pip` command path.
Note: `pip` path is not equal Vim Python's pip path.  Oh, no.
