### ISSUE TITLE
Message: rpc method [nvim_set_client_info] not implemented in neovim_rpc_methods.py

### ISSUE THREAD

**Issue by luizpara** [roxma/vim-hug-neovim-rpc#74]
There seems to already exist an [open issue about this problem](https://github.com/roxma/vim-hug-neovim-rpc/issues/59) posted in 2019, but it has not description whatsoever and thus, unsurprisingly, it did get no replies ever. So, because I am facing the same problem, I am posting a new issue with description and details in the hope that this issue can get more attention (and perhaps the other one may be merged to this).

Using Vim8, I have the following in my .vimrc file:

```
Plug 'ncm2/ncm2'
autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-jedi'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
```

However, every time I open a new buffer I get the error message:

> [vim-hug-neovim-rpc](https://github.com/roxma/vim-hug-neovim-rpc) rpc method [nvim_set_client_info] not implemented in pythonx/neovim_rpc_methods.py. Please send a PR or contact the mantainer.

I have tried searching for information about how solve it, but could not find any. Any help would be much appreciated.

**Comment by Shougo** [comment]
It works for me.

```vim
set rtp+=~/src/vim-hug-neovim-rpc
set rtp+=~/src/ncm2
set rtp+=~/src/ncm2-bufword
set rtp+=~/src/nvim-yarp

autocmd BufEnter * call ncm2#enable_for_buffer()
set completeopt=noinsert,menuone,noselect
```

What is your neovim version?

Oh, it must be Vim.

**Comment by Shougo** [comment]
https://github.com/roxma/vim-hug-neovim-rpc/issues/61

It is already fixed problem.  I think your plugin version is old.
