### ISSUE TITLE
vim-hug-neovim-rpc fail to work with python3.6.1 on archlinux

### ISSUE THREAD

**Issue by jsfaint** [roxma/vim-hug-neovim-rpc#8]
![image](https://user-images.githubusercontent.com/571829/27893101-1a459868-6236-11e7-9dfd-51713b721b50.png)

```
$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun  8 2017 20:51:28)
Included patches: 1-628
Compiled by Arch Linux
```

Same config works on windows with python3.5.3
When I switch to python2-neovim client, `vim-hug-neovim-rpc` works fine

**Comment by roxma** [comment]
Check the results in this order:

if `has('pythonx')`, then

  `:pythonx import neovim`

else if `has('python3')`, then 

  `:python3 import neovim`

else if `has('python2')`, then

  `:python2 import neovim`

**Comment by jsfaint** [comment]
echo has('pythonx') return 1
But `:pythonx import neovim` show below errors
![image](https://user-images.githubusercontent.com/571829/27894042-62d9713e-623c-11e7-9fe3-4007b0bf3478.png)

Interesting.. It looks when python2 and python3 both supported in vim, `:pythonx` will use python2 first

It's not bug of vim-hug-neovim-rpc, I'll close it.
Sorry for the interruption.

**Comment by roxma** [comment]
In this case, try adding `set pyxversion=3` into your vimrc.

**Comment by jsfaint** [comment]
@roxma it works! thank you~
